#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Nov 25 23:38:54 2018

@author: rishabh
"""

"""
Program to check if the given linkedlist is a palidrome or not.
"""


class Node:
    def __init__(self,data):
        self.data = data
        self.next = None
        
class LinkedList:
    def __init__(self):
        self.head = None
        self.last_node = None
        
    def append(self,data):
        
        if self.last_node is None:
            self.head = Node(data)
            self.last_node = self.head
        else:
            self.last_node.next = Node(data)
            self.last_node = self.last_node.next
            
    def get_prev_node(self, ref_node):
        current = self.head
        while(current and current.next != ref_node):
            current = current.next
        return current
    
def is_palindrome(llist):
    start = llist.head
    end = llist.last_node
    while (start != end and end.next != start):
        if start.data != end.data:
            return False
        start = start.next
        end = llist.get_prev_node(end)
    return True

a_llist = LinkedList()

data_list = '123454321'.split()
for data in data_list:
    a_llist.append(int(data))

if is_palindrome(a_llist):
    print('The linked list is palindromic.')
else:
    print('The linked list is not palindromic.')