#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Nov 25 15:43:03 2018

@author: rishabh
"""

"""
Create an algorithm that can partition a linkedlist around a given number
"""


class Node:
    def __init__(self,data):
        self.data = data
        self.next = None
        
class LinkedList:
    def __init__(self):
        self.head = None
        
    def push(self,new_data):
        new_node = Node(new_data)
        new_node.next = self.head
        self.head = new_node
        
    def partition(self,elem):
        
        tail = self.head
        curr = self.head
        
        while curr is not None:
            
            next = curr.next
            if curr.data < elem:
                curr.next = self.head
                self.head = curr
            
            else:
                tail.next = curr
                tail = curr
            
            curr = next
        
        tail.next = None
        
    def printList(self): 
        temp = self.head 
        while(temp): 
            print(" %d " %(temp.data), )
            temp = temp.next


llist = LinkedList() 
llist.push(3) 
llist.push(5) 
llist.push(10) 
llist.push(2) 
llist.push(8)

llist.printList()

llist.partition(5)
print("after partition")
llist.printList() 