#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 22 22:08:52 2018

@author: rishabh
"""

"""
Write a method to remove duplicates in an unsorted linkedlist
"""

"""
Most people make a mistake in this particular program because they solve it 
using a list data structure in python which is different from a link list data
structure a little. If an interviewer asks you to perform a duplicates from a
link list then you will first have to create a link list.
"""


"""
Create a node
"""

class Node:
    def __init__(self, data): # self in python is a way to call the current object.
        self.data = data
        self.next = None



"""
We next create a class LinkedList which containes a set of geenral methods in a
linked lists
"""
class LinkedList:
    def __init__(self):
        self.head = None
        self.last_node = None
 
    def append(self, data):
        if self.last_node is None:
            self.head = Node(data)
            self.last_node = self.head
        else:
            self.last_node.next = Node(data)
            self.last_node = self.last_node.next
 
    def get_prev_node(self, ref_node):
        current = self.head
        while (current and current.next != ref_node):
            current = current.next
        return current
 
    def remove(self, node):
        prev_node = self.get_prev_node(node)
        if prev_node is None:
            self.head = self.head.next
        else:
            prev_node.next = node.next
 
    def display(self):
        current = self.head
        while current:
            print(current.data, end = ' ')
            current = current.next
            
            
            
def remove_duplicates(llist):
    curr_l = llist.head
    while curr_l:
        data = curr_l.data
        curr_next = curr_l.next
        
        while curr_next:
            if curr_next.data == data:
                llist.remove(curr_next)
            curr_next = curr_next.next
        curr_l = curr_l.next
        
a_llist = LinkedList()

data_list = "1223224534235369"

for data in data_list:
    a_llist.append(int(data))

 
remove_duplicates(a_llist)

a_llist.display()
