#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 22 21:40:45 2018

@author: rishabh
"""

"""
String_Rotation: The challenge is that given two string str1 and str2. check if
the str2 is a subset of rotation of str1 or not. Condition is that the function
is_substring should only be called once.
"""

'''
Solution: Append string one to itself and make a new string and check if the
second string is a substring of new temp string. If it is then return true
else return false.
'''



def is_substring(str1,str2):
    return (str2 in str1)

def is_rotation(str1,str2):
    
    temp = str1+str1
    
    return is_substring(temp,str2)




print(is_rotation("watterbottle","terbottlewat"))
